package com.atlas.domain.model

data class AircraftApiAircraft(
    val registration: String,
    val aeroDataBoxId: Long?,
    val active: Boolean?,
    val serialNumber: String?,
    val hexIcao: String?,
    val airlineName: String?,
    val iataType: String?,
    val iataCodeShort: String?,
    val icaoCode: String?,
    val model: String?,
    val modelCode: String?,
    val numSeats: Int?,
    val rolloutDate: String?,
    val firstFlightDate: String?,
    val deliveryDate: String?,
    val registrationDate: String?,
    val typeName: String?,
    val numEngines: Int?,
    val engineType: String?,
    val isFreighter: Boolean?,
    val productionLine: String?,
    val ageYears: Double?,
    val verified: Boolean?,
    val imageUrl: String?,
    val imageWebUrl: String?,
    val imageAuthor: String?,
    val imageTitle: String?,
    val imageLicense: String?,
)
